/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package biirc;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author nihanth
 */
public class MacroEditor extends javax.swing.JDialog {

    private DefaultListModel mArgListModel = new DefaultListModel();
    private DefaultListModel mCmdListModel = new DefaultListModel();
    private Macro mMacro;
    private File mMacroFile;

    /** Creates new form MacroEditor */
    public MacroEditor(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
    }

    public MacroEditor(java.awt.Frame parent, File macroFile) {
        super(parent, true);
        initComponents();
        try {
            Macro m = Macro.loadFromFile(macroFile);
            keywordField.setText(m.getKeyword());
            syntaxField.setText(m.getSyntax());
            for (String arg : m.getArgs()) {
                mArgListModel.addElement(arg);
            }
            for (String cmd : m.getCommands()) {
                mCmdListModel.addElement(cmd);
            }
            mMacro = m;
            mMacroFile = macroFile;
        } catch (Exception e) {
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        keywordField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        argList = new javax.swing.JList(mArgListModel);
        jLabel4 = new javax.swing.JLabel();
        addArgumentBtn = new javax.swing.JButton();
        removeArgumentBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        cmdList = new javax.swing.JList(mCmdListModel);
        jLabel5 = new javax.swing.JLabel();
        addCmdBtn = new javax.swing.JButton();
        removeCmdBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        syntaxField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        saveBtn = new javax.swing.JButton();
        discardBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setModal(true);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Keyword");

        keywordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keywordFieldActionPerformed(evt);
            }
        });

        argList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(argList);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Arguments");

        addArgumentBtn.setText("+");
        addArgumentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addArgumentBtnActionPerformed(evt);
            }
        });

        removeArgumentBtn.setText("-");
        removeArgumentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeArgumentBtnActionPerformed(evt);
            }
        });

        cmdList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(cmdList);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Commands");

        addCmdBtn.setText("+");
        addCmdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCmdBtnActionPerformed(evt);
            }
        });

        removeCmdBtn.setText("-");
        removeCmdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeCmdBtnActionPerformed(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Syntax");

        syntaxField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                syntaxFieldActionPerformed(evt);
            }
        });

        saveBtn.setText("Save");
        saveBtn.setPreferredSize(new java.awt.Dimension(92, 29));
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        jPanel1.add(saveBtn);

        discardBtn.setText("Discard");
        discardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discardBtnActionPerformed(evt);
            }
        });
        jPanel1.add(discardBtn);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(jLabel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(jLabel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(addCmdBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(removeCmdBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(layout.createSequentialGroup()
                                        .add(addArgumentBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(removeArgumentBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                        .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                        .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(syntaxField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                    .add(keywordField))))
                        .add(0, 0, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(keywordField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(syntaxField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 81, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(addArgumentBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(removeArgumentBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jLabel4))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 81, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(addCmdBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(removeCmdBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jLabel5))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void keywordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keywordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keywordFieldActionPerformed

    private void addArgumentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addArgumentBtnActionPerformed
        String arg = JOptionPane.showInputDialog(this, "Enter argument name:");
        if (argList.getSelectedIndex() != -1)
            mArgListModel.add(argList.getSelectedIndex() + 1, arg);
        else
            mArgListModel.addElement(arg);
    }//GEN-LAST:event_addArgumentBtnActionPerformed

    private void removeArgumentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeArgumentBtnActionPerformed
        if (argList.getSelectedIndex() != -1) mArgListModel.remove(argList.getSelectedIndex());
    }//GEN-LAST:event_removeArgumentBtnActionPerformed

    private void addCmdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCmdBtnActionPerformed
        String cmd = JOptionPane.showInputDialog(this, "Enter comand:");
        if (cmdList.getSelectedIndex() != -1)
            mCmdListModel.add(cmdList.getSelectedIndex() + 1, cmd);
        else
            mCmdListModel.addElement(cmd);
    }//GEN-LAST:event_addCmdBtnActionPerformed

    private void removeCmdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeCmdBtnActionPerformed
        if (cmdList.getSelectedIndex() != -1) mCmdListModel.remove(cmdList.getSelectedIndex());
    }//GEN-LAST:event_removeCmdBtnActionPerformed

    private void syntaxFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_syntaxFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_syntaxFieldActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        String keyword = keywordField.getText();
        String syntax = syntaxField.getText();
        Object args[] = mArgListModel.toArray();
        Object commands[] = mCmdListModel.toArray();
        File f = new File(System.getProperty("user.home")
                + System.getProperty("file.separator")
                + "biIRC" + System.getProperty("file.separator")
                + "Macros" + System.getProperty("file.separator")
                + keyword + ".xml");
        try {
            if (!f.exists()) {
                f.getParentFile().mkdirs();
                f.createNewFile();
            }
            String indent = "    ";
            BufferedWriter bw = new BufferedWriter(new FileWriter(f));
            bw.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
            bw.newLine();
            bw.append("<biirc-macro>");
            bw.newLine();
            bw.append(indent).append("<syntax>").append(syntax).append("</syntax>");
            bw.newLine();
            bw.append(indent).append("<args>");
            bw.newLine();
            for (Object arg : args) {
                bw.append(indent).append(indent).append("<arg>").append(arg.toString()).append(
                        "</arg>");
                bw.newLine();
            }
            bw.append(indent).append("</args>");
            bw.newLine();
            bw.append(indent).append("<commands>");
            bw.newLine();
            for (Object cmd : commands) {
                bw.append(indent).append(indent).append("<cmd>").append(cmd.toString()).append(
                        "</cmd>");
                bw.newLine();
            }
            bw.append(indent).append("</commands>");
            bw.newLine();
            bw.append("</biirc-macro>");
            bw.newLine();
            bw.flush();
            bw.close();
            dispose();
            if (mMacro != null && mMacroFile != null && !mMacro.getKeyword().equals(keyword))
                mMacroFile.delete();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error while saving macro file: " + e.getMessage());
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void discardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discardBtnActionPerformed
        dispose();
    }//GEN-LAST:event_discardBtnActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addArgumentBtn;
    private javax.swing.JButton addCmdBtn;
    private javax.swing.JList argList;
    private javax.swing.JList cmdList;
    private javax.swing.JButton discardBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField keywordField;
    private javax.swing.JButton removeArgumentBtn;
    private javax.swing.JButton removeCmdBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField syntaxField;
    // End of variables declaration//GEN-END:variables
}
